### ISSUE TITLE
StarknetErrorCode.OUT_OF_RANGE_FEE

### ISSUE THREAD

**Issue by Qupday** [0xs34n/starknet.js-workshop#5]
I have install lastest version of starknet
const initializeResponse = await accountContract.initialize(starkKeyPub, "0");
when call accountContract.initialize,catch exception: GatewayError: max_fee must be bigger than 0. errorCode: 'StarknetErrorCode.OUT_OF_RANGE_FEE'

**Comment by ivpavici** [comment]
Hi, 
This issue should be fixed with latest introduced changes!
